# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41f9a8d6d32178eacbdfd1206b8ea3ed2e0ad4a13976fc5c97c19dded67f790895167be6fc97fde9fabc5637240643b910895248fe1bf1f457164575ef725932

test:
  secret_key_base: 54b5c424566dca0f7da9b5fccdc8114e6e96f4ea83e1f534f2540d782550ea12acb7eb32fc54e9764379a635ab300a6a451205d7131c232ffbbb5c37c720bb36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
